### ISSUE TITLE
Could not pass event LingeringPotionSplashEvent to PlotSquared

### ISSUE THREAD

**Issue by ds58** [Ruinscraft/PlotCubed#13]
```
java.lang.NoSuchMethodError: org.bukkit.event.entity.LingeringPotionSplashEvent.getEntity()Lorg/bukkit/entity/ThrownPotion;
	at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onPotionSplash(PlayerEvents.java:1716) ~[?:?]```

**Comment by ds58** [comment]
Still an issue
```
[16:56:49] [Server thread/ERROR]: Could not pass event LingeringPotionSplashEvent to PlotSquared v4.9999
java.lang.NoSuchMethodError: org.bukkit.event.entity.LingeringPotionSplashEvent.getEntity()Lorg/bukkit/entity/ThrownPotion;
	at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onPotionSplash(PlayerEvents.java:1784) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor71.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callLingeringPotionSplashEvent(CraftEventFactory.java:552) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at net.minecraft.server.v1_13_R2.EntityPotion.a(EntityPotion.java:213) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at net.minecraft.server.v1_13_R2.EntityPotion.a(EntityPotion.java:88) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at net.minecraft.server.v1_13_R2.EntityProjectile.tick(EntityProjectile.java:161) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1568) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1535) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1346) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-69c10529]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]```

**Comment by ds58** [comment]
not an issue with v5
