### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by ds58** [Ruinscraft/PlotCubed#3]
```[14:09:50 WARN]: [PlotSquared] Task #849 for PlotSquared v4.-2029 generated an exception
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_212]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_212]
        at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_212]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
        at com.github.intellectualsites.plotsquared.plot.commands.Timer.lambda$static$0(Timer.java:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by ds58** [comment]
Hasn't happened since. Hopefully upstream will handle it if its an issue for others
