### ISSUE TITLE
NPE on shutdown

### ISSUE THREAD

**Issue by ds58** [Ruinscraft/PlotCubed#7]
```
[04:25:54] [Server thread/WARN]: java.lang.NullPointerException
[04:25:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.util.StringMan$1.compare(StringMan.java:150)
[04:25:54] [Server thread/WARN]: 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
[04:25:54] [Server thread/WARN]: 	at java.util.TimSort.sort(TimSort.java:220)
[04:25:54] [Server thread/WARN]: 	at java.util.Arrays.sort(Arrays.java:1438)
[04:25:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.util.StringMan.joinOrdered(StringMan.java:148)
[04:25:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.database.SQLManager.validateAllPlots(SQLManager.java:3150)
[04:25:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.database.DBFunc.validatePlots(DBFunc.java:74)
[04:25:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.PlotSquared.disable(PlotSquared.java:1524)
[04:25:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.onDisable(BukkitMain.java:269)
[04:25:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[04:25:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[04:25:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[04:25:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[04:25:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[04:25:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[04:25:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:652)
[04:25:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:874)
[04:25:54] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[04:25:54] [Server thread/INFO]: Could not close database connection!

**Comment by ds58** [comment]
Hasn't happened since. Hopefully upstream will take care of it if its an issue for others
